version: 2.1
orbs:
  go: circleci/go@1.7.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.19.2' # Specify a version tag
    steps:
      - checkout # checkout source code
      - run:
          command: echo 'load go cache'
          name: Load cache
      - run:
          command: echo 'mod download cache'
          name: Mod download
      - run:
          command: echo 'go save cache'
          name: Save cache
      - run:
          command: echo 'Go test'
          name: Go test
      - persist_to_workspace:
          root: ~/project
          paths: .

  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: heroku/deploy-via-git
          command: |
            echo 'Go Command to deploy to Heroku'

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
