version: 2.1

jobs:
  pr-clean-up:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

workflows:
  pr-clean-up:
    jobs:
      - pr-clean-up
