version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: node/install-packages
          command: |
            echo 'Node Command to install yarn packages'
      - run:
          command: echo 'run yarn tests'
          name: Run Yarn tests
      - run:
          command: echo 'build app build'
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: heroku/deploy-via-git
          command: |
            echo 'node command to deploy to Heroku'

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
